const ENV_VARIABLES = {
	DBURL: process.env.DBURL,
	ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
	REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
	ACCESS_TOKEN_VALIDITY: process.env.ACCESS_TOKEN_VALIDITY,
	REFRESH_TOKEN_VALIDITY: process.env.REFRESH_TOKEN_VALIDITY,
};

const USER_ROLES = {
	SUPER_ADMIN: 'SUPER_ADMIN',
	BUYER: 'BUYER',
	SELLER: 'SELLER',
	INDIVIDUAL_SELLER: 'INDIVIDUAL_SELLER',
};

const FIREBASE_KEYS = {
	FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGE_SENDER_ID: process.env.FIREBASE_MESSAGE_SENDER_ID,
	FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
	FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
};

module.exports = {
	ENV_VARIABLES,
	USER_ROLES,
	FIREBASE_KEYS,
};
